import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Data Structures",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
      <footer>
        <span>
          Dave Ogle 2026: (<a href="mailto:dave.ogle@pm.me">dave.ogle@pm.me</a>)
        </span>
      </footer>
    </>
  );
}
